server.port=8085
server.address=127.0.0.1

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.generate-ddl=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Configuracion JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Directorio de archivos en produccion
nominas.upload-dir=/var/workzen/uploads/nominas
documentos.upload.dir=/var/workzen/uploads/documentos
justificantes.upload-dir=/var/workzen/uploads/justificantes

# Swagger desactivado en produccion
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

